/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurMesureRouteImport } from './routes/sur-mesure'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as CreatriceRouteImport } from './routes/creatrice'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CarnetRouteImport } from './routes/carnet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as CarnetIndexRouteImport } from './routes/carnet.index'
import { Route as PreviewNewsletterRouteImport } from './routes/preview.newsletter'
import { Route as PreviewLoadersRouteImport } from './routes/preview.loaders'
import { Route as PreviewLeadcaptureRouteImport } from './routes/preview.leadcapture'
import { Route as PreviewHeroRouteImport } from './routes/preview.hero'
import { Route as PreviewFooterRouteImport } from './routes/preview.footer'
import { Route as PreviewEtabliRouteImport } from './routes/preview.etabli'
import { Route as PreviewContactRouteImport } from './routes/preview.contact'
import { Route as PreviewCollectionRouteImport } from './routes/preview.collection'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as CarnetSlugRouteImport } from './routes/carnet.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SurMesureRoute = SurMesureRouteImport.update({
  id: '/sur-mesure',
  path: '/sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatriceRoute = CreatriceRouteImport.update({
  id: '/creatrice',
  path: '/creatrice',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetRoute = CarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRoute,
} as any)
const CarnetIndexRoute = CarnetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarnetRoute,
} as any)
const PreviewNewsletterRoute = PreviewNewsletterRouteImport.update({
  id: '/preview/newsletter',
  path: '/preview/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewLoadersRoute = PreviewLoadersRouteImport.update({
  id: '/preview/loaders',
  path: '/preview/loaders',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewLeadcaptureRoute = PreviewLeadcaptureRouteImport.update({
  id: '/preview/leadcapture',
  path: '/preview/leadcapture',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHeroRoute = PreviewHeroRouteImport.update({
  id: '/preview/hero',
  path: '/preview/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewFooterRoute = PreviewFooterRouteImport.update({
  id: '/preview/footer',
  path: '/preview/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewEtabliRoute = PreviewEtabliRouteImport.update({
  id: '/preview/etabli',
  path: '/preview/etabli',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewContactRoute = PreviewContactRouteImport.update({
  id: '/preview/contact',
  path: '/preview/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCollectionRoute = PreviewCollectionRouteImport.update({
  id: '/preview/collection',
  path: '/preview/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionRoute,
} as any)
const CarnetSlugRoute = CarnetSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarnetRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carnet': typeof CarnetRouteWithChildren
  '/cgv': typeof CgvRoute
  '/collection': typeof CollectionRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/creatrice': typeof CreatriceRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sur-mesure': typeof SurMesureRoute
  '/carnet/$slug': typeof CarnetSlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/preview/collection': typeof PreviewCollectionRoute
  '/preview/contact': typeof PreviewContactRoute
  '/preview/etabli': typeof PreviewEtabliRoute
  '/preview/footer': typeof PreviewFooterRoute
  '/preview/hero': typeof PreviewHeroRoute
  '/preview/leadcapture': typeof PreviewLeadcaptureRoute
  '/preview/loaders': typeof PreviewLoadersRoute
  '/preview/newsletter': typeof PreviewNewsletterRoute
  '/carnet/': typeof CarnetIndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/creatrice': typeof CreatriceRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sur-mesure': typeof SurMesureRoute
  '/carnet/$slug': typeof CarnetSlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/preview/collection': typeof PreviewCollectionRoute
  '/preview/contact': typeof PreviewContactRoute
  '/preview/etabli': typeof PreviewEtabliRoute
  '/preview/footer': typeof PreviewFooterRoute
  '/preview/hero': typeof PreviewHeroRoute
  '/preview/leadcapture': typeof PreviewLeadcaptureRoute
  '/preview/loaders': typeof PreviewLoadersRoute
  '/preview/newsletter': typeof PreviewNewsletterRoute
  '/carnet': typeof CarnetIndexRoute
  '/collection': typeof CollectionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carnet': typeof CarnetRouteWithChildren
  '/cgv': typeof CgvRoute
  '/collection': typeof CollectionRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/creatrice': typeof CreatriceRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sur-mesure': typeof SurMesureRoute
  '/carnet/$slug': typeof CarnetSlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/preview/collection': typeof PreviewCollectionRoute
  '/preview/contact': typeof PreviewContactRoute
  '/preview/etabli': typeof PreviewEtabliRoute
  '/preview/footer': typeof PreviewFooterRoute
  '/preview/hero': typeof PreviewHeroRoute
  '/preview/leadcapture': typeof PreviewLeadcaptureRoute
  '/preview/loaders': typeof PreviewLoadersRoute
  '/preview/newsletter': typeof PreviewNewsletterRoute
  '/carnet/': typeof CarnetIndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carnet'
    | '/cgv'
    | '/collection'
    | '/confidentialite'
    | '/contact'
    | '/creatrice'
    | '/mentions-legales'
    | '/sur-mesure'
    | '/carnet/$slug'
    | '/collection/$slug'
    | '/preview/collection'
    | '/preview/contact'
    | '/preview/etabli'
    | '/preview/footer'
    | '/preview/hero'
    | '/preview/leadcapture'
    | '/preview/loaders'
    | '/preview/newsletter'
    | '/carnet/'
    | '/collection/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/creatrice'
    | '/mentions-legales'
    | '/sur-mesure'
    | '/carnet/$slug'
    | '/collection/$slug'
    | '/preview/collection'
    | '/preview/contact'
    | '/preview/etabli'
    | '/preview/footer'
    | '/preview/hero'
    | '/preview/leadcapture'
    | '/preview/loaders'
    | '/preview/newsletter'
    | '/carnet'
    | '/collection'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/carnet'
    | '/cgv'
    | '/collection'
    | '/confidentialite'
    | '/contact'
    | '/creatrice'
    | '/mentions-legales'
    | '/sur-mesure'
    | '/carnet/$slug'
    | '/collection/$slug'
    | '/preview/collection'
    | '/preview/contact'
    | '/preview/etabli'
    | '/preview/footer'
    | '/preview/hero'
    | '/preview/leadcapture'
    | '/preview/loaders'
    | '/preview/newsletter'
    | '/carnet/'
    | '/collection/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarnetRoute: typeof CarnetRouteWithChildren
  CgvRoute: typeof CgvRoute
  CollectionRoute: typeof CollectionRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CreatriceRoute: typeof CreatriceRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SurMesureRoute: typeof SurMesureRoute
  PreviewCollectionRoute: typeof PreviewCollectionRoute
  PreviewContactRoute: typeof PreviewContactRoute
  PreviewEtabliRoute: typeof PreviewEtabliRoute
  PreviewFooterRoute: typeof PreviewFooterRoute
  PreviewHeroRoute: typeof PreviewHeroRoute
  PreviewLeadcaptureRoute: typeof PreviewLeadcaptureRoute
  PreviewLoadersRoute: typeof PreviewLoadersRoute
  PreviewNewsletterRoute: typeof PreviewNewsletterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sur-mesure': {
      id: '/sur-mesure'
      path: '/sur-mesure'
      fullPath: '/sur-mesure'
      preLoaderRoute: typeof SurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatrice': {
      id: '/creatrice'
      path: '/creatrice'
      fullPath: '/creatrice'
      preLoaderRoute: typeof CreatriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet': {
      id: '/carnet'
      path: '/carnet'
      fullPath: '/carnet'
      preLoaderRoute: typeof CarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/carnet/': {
      id: '/carnet/'
      path: '/'
      fullPath: '/carnet/'
      preLoaderRoute: typeof CarnetIndexRouteImport
      parentRoute: typeof CarnetRoute
    }
    '/preview/newsletter': {
      id: '/preview/newsletter'
      path: '/preview/newsletter'
      fullPath: '/preview/newsletter'
      preLoaderRoute: typeof PreviewNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/loaders': {
      id: '/preview/loaders'
      path: '/preview/loaders'
      fullPath: '/preview/loaders'
      preLoaderRoute: typeof PreviewLoadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/leadcapture': {
      id: '/preview/leadcapture'
      path: '/preview/leadcapture'
      fullPath: '/preview/leadcapture'
      preLoaderRoute: typeof PreviewLeadcaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/hero': {
      id: '/preview/hero'
      path: '/preview/hero'
      fullPath: '/preview/hero'
      preLoaderRoute: typeof PreviewHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/footer': {
      id: '/preview/footer'
      path: '/preview/footer'
      fullPath: '/preview/footer'
      preLoaderRoute: typeof PreviewFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/etabli': {
      id: '/preview/etabli'
      path: '/preview/etabli'
      fullPath: '/preview/etabli'
      preLoaderRoute: typeof PreviewEtabliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/contact': {
      id: '/preview/contact'
      path: '/preview/contact'
      fullPath: '/preview/contact'
      preLoaderRoute: typeof PreviewContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/collection': {
      id: '/preview/collection'
      path: '/preview/collection'
      fullPath: '/preview/collection'
      preLoaderRoute: typeof PreviewCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/carnet/$slug': {
      id: '/carnet/$slug'
      path: '/$slug'
      fullPath: '/carnet/$slug'
      preLoaderRoute: typeof CarnetSlugRouteImport
      parentRoute: typeof CarnetRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CarnetRouteChildren {
  CarnetSlugRoute: typeof CarnetSlugRoute
  CarnetIndexRoute: typeof CarnetIndexRoute
}

const CarnetRouteChildren: CarnetRouteChildren = {
  CarnetSlugRoute: CarnetSlugRoute,
  CarnetIndexRoute: CarnetIndexRoute,
}

const CarnetRouteWithChildren =
  CarnetRoute._addFileChildren(CarnetRouteChildren)

interface CollectionRouteChildren {
  CollectionSlugRoute: typeof CollectionSlugRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionSlugRoute: CollectionSlugRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarnetRoute: CarnetRouteWithChildren,
  CgvRoute: CgvRoute,
  CollectionRoute: CollectionRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CreatriceRoute: CreatriceRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SurMesureRoute: SurMesureRoute,
  PreviewCollectionRoute: PreviewCollectionRoute,
  PreviewContactRoute: PreviewContactRoute,
  PreviewEtabliRoute: PreviewEtabliRoute,
  PreviewFooterRoute: PreviewFooterRoute,
  PreviewHeroRoute: PreviewHeroRoute,
  PreviewLeadcaptureRoute: PreviewLeadcaptureRoute,
  PreviewLoadersRoute: PreviewLoadersRoute,
  PreviewNewsletterRoute: PreviewNewsletterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
